### ISSUE TITLE
node-gyp build -> fail on Windows 7 x64 -> Platform for project invalid ?

### ISSUE THREAD

**Issue by fperreault** [node-hid/node-hid#19]
I have this error:
"C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.Cpp.InvalidPlatform
.Targets(23,7): error MSB8007: The Platform for project 'hidapi.vcxproj' is inv
alid.  Platform='x64'. You may be seeing this message because you are trying to
 build a project without a solution file, and have specified a non-default Plat
form that doesn't exist for this project. [C:\Users\fperreault\Desktop\hid\buil
d\hidapi.vcxproj]"

How can I resolve it.
Can you help me.
Here the compilation log:

C:\Users\fperreault\Desktop\hid>node-gyp configure
gyp info it worked if it ends with ok
gyp info using node-gyp@0.7.1
gyp info using node@0.8.12 | win32 | x64
gyp info spawn C:\Python27\python.exe
gyp info spawn args [ 'C:\Users\fperreault\.node-gyp\0.8.12\tools\gyp\gyp
',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2010',
gyp info spawn args   '-I',
gyp info spawn args   'C:\Users\fperreault\Desktop\hid\build\config.gypi',

gyp info spawn args   '-I',
gyp info spawn args   'C:\Users\fperreault\AppData\Roaming\npm\node_module
s\node-gyp\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\Users\fperreault\.node-gyp\0.8.12\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\Users\fperreault\.node-gyp\0.8.12'
,
gyp info spawn args   '-Dmodule_root_dir=C:\Users\fperreault\Desktop\hid',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\Users\fperreault\Desktop\hid\build',
gyp info spawn args   '-Goutput_dir=.' ]
Warning: Missing input files:
C:\Users\fperreault\Desktop\hid\build..\hidapi\windows\hid.c
gyp info ok

C:\Users\fperreault\Desktop\hid>node-gyp build
gyp info it worked if it ends with ok
gyp info using node-gyp@0.7.1
gyp info using node@0.8.12 | win32 | x64
gyp info spawn C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/property:TargetExt=.node',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.Cpp.InvalidPlatform
.Targets(23,7): error MSB8007: The Platform for project 'hidapi.vcxproj' is inv
alid.  Platform='x64'. You may be seeing this message because you are trying to
 build a project without a solution file, and have specified a non-default Plat
form that doesn't exist for this project. [C:\Users\fperreault\Desktop\hid\buil
d\hidapi.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\fperreault\AppData\Roaming\n
pm\node_modules\node-gyp\lib\build.js:236:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:96:17)
gyp ERR! stack     at Process._handle.onexit (child_process.js:678:10)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\Users\fperreault\AppData\Roaming\npm\node_modu
les\node-gyp\bin\node-gyp.js" "build"
gyp ERR! cwd C:\Users\fperreault\Desktop\hid
gyp ERR! node -v v0.8.12
gyp ERR! node-gyp -v v0.7.1
gyp ERR! not ok

thank you

**Comment by bartread** [comment]
Nope. Doesn't work at all for me installing pretty much any package that requires node-gyp - the current bugbear being contextify, which is a dependency of grunt-dom-munger.

Here's my setup:

- Windows 8 (64-bit, obviously)
- Windows 8 SDK
- Visual C++ 2010 Express
- Visual Studio 2012 Ultimate
- Visual Studio 2013 Ultimate
- Python 2.7.3
- Node 0.10.37, but I get the same results with 0.12.0 (I'm using nvm-windows to manage multiple versions)

If I try to `npm install` using the VC++ 2010 tools it moans at me that the platform is invalid:

```
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.Cpp.InvalidPlatform.Targets(23,7): error MSB8007: The Platform for project 'contextify.vcxproj' is
invalid.  Platform='x64'. You may be seeing this message because you are trying to build a project without a solution file, and have specified a non-default Pl
atform that doesn't exist for this project. [C:\GitWork\chosen\node_modules\grunt-dom-munger\node_modules\jsdom\node_modules\contextify\build\contextify.vcxpro
j]
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Bart\AppData\Roaming\nvm\v0.10.37\node_modules\npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Windows_NT 6.2.9200
gyp ERR! command "node" "C:\\Users\\Bart\\AppData\\Roaming\\nvm\\v0.10.37\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\GitWork\chosen\node_modules\grunt-dom-munger\node_modules\jsdom\node_modules\contextify
gyp ERR! node -v v0.10.37
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok
npm WARN optional dep failed, continuing jsdom@0.5.7
```

If I try to `npm install` using the VC++ 2012 tools (native tools command prompt) it moans that it can't find the tools for 2010:

```
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V110\Microsoft.Cpp.Platform.targets(42,5): error MSB8020: The builds tools for Visual Studio 2010 (Platform T
oolset = 'v100') cannot be found. To build using the v100 build tools, either click the Project menu or right-click the solution, and then select "Update VC++
Projects...". Install Visual Studio 2010 to build using the Visual Studio 2010 build tools. [C:\GitWork\chosen\node_modules\grunt-dom-munger\node_modules\jsdom
\node_modules\contextify\build\contextify.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Bart\AppData\Roaming\nvm\v0.10.37\node_modules\npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Windows_NT 6.2.9200
gyp ERR! command "node" "C:\\Users\\Bart\\AppData\\Roaming\\nvm\\v0.10.37\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\GitWork\chosen\node_modules\grunt-dom-munger\node_modules\jsdom\node_modules\contextify
gyp ERR! node -v v0.10.37
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok
npm WARN optional dep failed, continuing jsdom@0.5.7
```

I can't really edit the project file or platform settings because it's a child dependency, otherwise I would have tried that already too.

If anyone has any suggestions I'd be very grateful to hear them.


Thanks,


Bart

**Comment by bartread** [comment]
Maybe that's it. Maybe I've gone too far. Node on Windows 8 under Parallels on OSX? Maybe it's too many levels. Maybe I'm in Limbo.

Of course, when I clone and run `npm install` on OSX it "just works". Honestly, there's never an airline sickbag around when you need one.

**Comment by rinie** [comment]
Are you using 32 bits Node or 64 bits?
VC2010 only works for 32 bits node (on 64 bits windows)


2015-03-20 16:41 GMT+01:00 Bart Read <notifications@github.com>:

> Maybe that's it. Maybe I've gone too far. Node on Windows 8 under
> Parallels on OSX? Maybe it's too many levels. Maybe I'm in Limbo.
>
> Of course, when I clone and run npm install on OSX it "just works".
> Honestly, there's never an airline sickbag around when you need one.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/node-hid/node-hid/issues/19#issuecomment-84051866>.
>



-- 
Met vriendelijke groeten,
 Rinie Kervel.

Don't walk behind me, I may not lead.
Don't walk in front of me, I may not follow.
Just walk beside me and be my friend.

**Comment by odingalt** [comment]
I get a lot of nanthrowerror

C:\TEMP\bootloader-jsx\node_modules\node-hid>node-gyp build --msvs_version=2013
| more
gyp info it worked if it ends with ok
gyp info using node-gyp@3.0.3
gyp info using node@4.0.0 | win32 | x64
gyp info spawn msbuild
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
  hidapi.vcxproj -> C:\TEMP\bootloader-jsx\node_modules\node-hid\build\Release\\
hidapi.lib
  HID.cc
..\src\HID.cc(51): error C3861: 'NanThrowError': identifier not found [C:\TEMP\b
ootloader-jsx\node_modules\node-hid\build\HID.vcxproj]
..\src\HID.cc(67): warning C4290: C++ exception specification ignored except to
indicate a function is not __declspec(nothrow) [C:\TEMP\bootloader-jsx\node_modu
les\node-hid\build\HID.vcxproj]
..\src\HID.cc(70): warning C4290: C++ exception specification ignored except to
indicate a function is not __declspec(nothrow) [C:\TEMP\bootloader-jsx\node_modu
les\node-hid\build\HID.vcxproj]
..\src\HID.cc(92): error C2061: syntax error : identifier 'NanCallback' [C:\TEMP
\bootloader-jsx\node_modules\node-hid\build\HID.vcxproj]
..\src\HID.cc(106): error C2143: syntax error : missing ';' before '*' [C:\TEMP\
bootloader-jsx\node_modules\node-hid\build\HID.vcxproj]
.... (the list goes on)

C:\TEMP\bootloader-jsx\node_modules\node-hid>npm -v
2.14.3

C:\TEMP\bootloader-jsx\node_modules\node-hid>node -v
v4.0.0

C:\TEMP\bootloader-jsx\node_modules\node-hid>node-gyp -v
v3.0.3
