### ISSUE TITLE
If open more than four device, the “hid.on('data', (data) => { console.log('data')})” will not recieve any data

### ISSUE THREAD

**Issue by yefengong** [node-hid/node-hid#528]
If open more than four device, the “hid.on('data', (data) => { console.log('data')})” will not recieve any data

**Comment by Julusian** [comment]
this is a known limitation of the sync api https://github.com/node-hid/node-hid#async-vs-sync-api

**Comment by yefengong** [comment]
Thank you. I was really too hasty and didn't notice the content in the document. Thank you again.
