### ISSUE TITLE
Segmentation Fault on both Deno and Bun

### ISSUE THREAD

**Issue by Repugraf** [node-hid/node-hid#532]
Everything works as expected on node.js but when library is tested with Deno or Bun runtime everything starts to fail.

I suppose this is the issue with deno and bun. But could you share insight why it's failing for them?
Does it have to do something with Rust and Zig?
Maybe there is some issues they need to fix?

I doubt this is the issue only with node-hid library. Probably this kind of issues are happening with other libraries.

It does fails only if you attach on data listener:

```js
const device = new HID(vendorId, productId); // everything is fine

/**
 * DENO:
 * zsh: segmentation fault  deno run -A test.mjs
 *
 * BUN:
 * Message received: Buffer(19) [ 0, 0, 0, 0, 4, 0, 4, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0 ]
 * Message received: Buffer(19) [ 0, 0, 0, 0, 4, 0, 4, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0 ]
 * zsh: segmentation fault  bun test.mjs
 */
device.on("data", buffer => console.log("Message received:", buffer));
```

Device tested: MacOS M1 chip

**Comment by Julusian** [comment]
Could be hitting https://github.com/denoland/deno/issues/21376

And bun doesn't have full node-api coverage https://github.com/oven-sh/bun/issues/158, so it is expected to not work there. From a quick skim we are using `napi_open_escapable_handle_scope`, possibly other methods they havent implemented

**Comment by Repugraf** [comment]
Just tested with deno `1.46.1` and it works. Also it seems that the issue was fixed https://github.com/denoland/deno/issues/21376

**Comment by Repugraf** [comment]
Just tested bun `1.1.26` and it works. Issue mentioned by @Julusian is not fixed but probably another issue causing seg fault was fixed

**Comment by Repugraf** [comment]
It seems that both deno and bun fixed the issue on their side and it looks like this issue can be closed.
