### ISSUE TITLE
Is there a way to get input report with the report id?

### ISSUE THREAD

**Issue by WShiBin** [node-hid/node-hid#539]
I'm new with the hid.
In my case, can't recive data with the `device.on('data', function(data) {} )`;

I have another examples that use [`HidD_GetInputReport `](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/hidsdi/nf-hidsdi-hidd_getinputreport) works fine. Becouse the second argument which include the report id.
So, like the title. Is there a way/api to get input report with the report id? 

Any suggest? Or documents must be read?

**Comment by Julusian** [comment]
No, there isn't an equivalent for that currently.

**Comment by WShiBin** [comment]
I add it myself. works well.

**Comment by favour1025** [comment]
在mac os系统上无法使用device.on('data', function(data) {} )接收数据，怎么解决呢
