### ISSUE TITLE
"node-hid fails install" OSX 10.9.2 - common.gypi issue

### ISSUE THREAD

**Issue by ajfisher** [node-hid/node-hid#63]
I've seen others have similar issues but I think this was caused by a mavericks upgrade.

OSX: 10.9.2
Homebrew: Up to date
XCode: Up to date
Command line tools: up to date
Node: 0.10.26
NPM: 1.4.3
Python: 2.7.6

So I'm getting the notorious "sh install.sh" issue. But looking through the stack there's an issue with not finding the common.gypi file:

gyp: /Users/ajfisher/.node-gyp/0.10.26/common.gypi not found (cwd: /Users/ajfisher/dev/nbdmelb/nbdmelb/simplebot/node_modules/node-hid) while reading includes of binding.gyp

I'm not sure why this all got out of sync (a previous common.gypi file existed in 0.10.15 but was compiled for Mountain Lion). So basically I nuked the .node-gyp folder and started with a fresh npm install of everything and it all worked fine.

More FYI for future peeps than anything.

**Comment by skilbjo** [comment]
+1 me too, same configuration yet same errors

**Comment by natevw** [comment]
Can you give a try with https://github.com/node-hid/node-hid/pull/95 and see if those changes help?

**Comment by natevw** [comment]
I'm going to assume this is fixed via #95 as of node-hid@0.4.0 — otherwise please let me know if this needs to be reopened.
