### ISSUE TITLE
can not open device of path defined (temperature sensor)

### ISSUE THREAD

**Issue by anupam19** [node-hid/node-hid#71]
I am having problem but not getting any solution. I am using temperature sensor from pcsensor.com
I can read data via C program they have given. 
I am using this temper1 node : https://www.npmjs.org/package/temper1
This sensor is a different than my one and hence I changed the sensor name and interface  in temper code.
also I had to add functionGlobalContext: { thermometers:require('temper1') } in node red settings file to access from function

I can get device attributes writing this in function block:

var devices = context.global.thermometers.getDevices();
return devices;

I am getting this as output : 
(Object) { "vendorId": 3141, "productId": 29697, "path": "0006:0005:00", "manufacturer": "RDing", "product": "TEMPerV1.4", "release": 1, "interface": 0 }

Now I tried this to get data:

var device = context.global.thermometers.readTemperature("0006:0005:00", function(err, value) {
  console.log("Result:"+value);
});
return device;

I am getting:

cannot open device with path 0006:0005:00

i have set udev rule to access as non-root user and I tested it as working when I am accessing via C program by the sensor provider. I am not getting why It can not read data, even I tried to get data using node-hid too

**Comment by herrjemand** [comment]
Ref: #64
