### ISSUE TITLE
node-hid with node-webkit

### ISSUE THREAD

**Issue by mirzadelic** [node-hid/node-hid#82]
I am trying to use node-hid with node-webkit on Windows XP, but i am getting error:
```
Error: Module did not self-register
```

running with command `nwbuild . -rw`

node version: 0.10.32
node-webkit version: 0.10.5

What is solution?

**Comment by amullins83** [comment]
Any idea why node-hid is incompatible with nw 0.10.5? What changed?

**Comment by natevw** [comment]
Can you give a try with https://github.com/node-hid/node-hid/pull/95 and report there any issues you're still having?

**Comment by natevw** [comment]
This is most likely fixed via #95, as of node-hid@0.4.0. This is one specific use case I haven't tried specifically, but in this new version the way the build is done is now much more standard. It used to use a separate script to first checkout the HIDAPI repo and then manually call a node-gyp itself. This caused trouble with atom-shell/Electron and probably node-webkit as well though IIRC there was some workaround for the latter. Now the HIDAPI source is published with the package and the bindings are automatically built with no intervening script — so if your build system handles pretty much any other native GYP binding it should be able to handle this now too.

Anyway, having not heard back from the initial test I'm going to go ahead and optimistically close this. Please let me know if there's still an issue.
