### ISSUE TITLE
node-hid cannot read reports from Sony DualShock 4 over bluetooth on Mac OS X 10.10

### ISSUE THREAD

**Issue by Bluebie** [node-hid/node-hid#83]
node-hid can discover devices and raises no errors, and continues to work as usual over usb. When connected via bluetooth, the 'data' event never fires, and async read() calls never fire their callback.

I'm going to try and reproduce this with other hid devices later. There have been some reports of general bluetooth connectivity problems in OS 10.10.0, so maybe the bluetooth stack has been updated or replaced. Unfortunately the bluetooth stack is closed source, so any changes are fairly opaque. Interestingly @creationix's gamepad npm module still works. I'd like to figure out why this isn't working as I want to support some more specialised features of the device.

**Comment by Auine** [comment]
have the same problem
